/* This file was generated by syncqt. */
#ifndef QT_QTOPENGL_VERSION_H
#define QT_QTOPENGL_VERSION_H

#define QTOPENGL_VERSION_STR "5.15.10"

#define QTOPENGL_VERSION 0x050F0A

#endif // QT_QTOPENGL_VERSION_H
